services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: teknos_logistics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - teknos-logistics-db:/var/lib/postgresql/data

volumes:
  teknos-logistics-db:
